### PR TITLE
feat: add mjs support by add package.json

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by aeschli** [comment]
Is it necessary that we change all import to include `.js`?

**Comment by xiaoxiangmoe** [comment]
Because TypeScript does not support generating `.js` suffix names. And esm must use the suffix name `.js`.

**Comment by xiaoxiangmoe** [comment]
If you do not change the source code, then we can only consider using rollup to package esm.

**Comment by aeschli** [comment]
Closing. I need more help here to understand what the advantages are.

**Pull request closed without merging**
